const serializeUser = (user) => ({
  _id: user._id,
  name: user.name,
  email: user.email,
  phone: user.phone,
  role: user.role,
  instituteId: user.instituteId?._id || user.instituteId || null,
  institute: user.instituteId?.name ? user.instituteId : null,
  employeeId: user.employeeId,
  qualification: user.qualification,
  experience: user.experience,
  department: user.department,
  assignedAcademicGroups: user.assignedAcademicGroups,
  relation: user.relation,
  linkedStudentIds: user.linkedStudentIds,
  address: user.address,
  staffId: user.staffId,
  joiningDate: user.joiningDate,
  salary: user.salary,
  designation: user.designation,
  permissions: user.permissions,
  status: user.status,
  profilePhoto: user.profilePhoto,
  createdBy: user.createdBy,
  createdAt: user.createdAt,
  updatedAt: user.updatedAt,
});

export { serializeUser };
